export { default as PuzzleGame } from './PuzzleGame';
export { default as DrawingPad } from './DrawingPad';
export { default as MemoryGame } from './MemoryGame';
export { default as BubbleGame } from './BubbleGame';
export { default as SimonGame } from './SimonGame';
export { default as CatchGame } from './CatchGame';
export { default as GardeningGame } from './GardeningGame';
export { default as CookingGame } from './CookingGame';
export { default as QuizGame } from './QuizGame';
