# Surfboard (onde.surf) Cloudflare Pages Deployment
# PROTECTED: Only tech-support agent can deploy via manual trigger with passphrase
# NO AUTO-DEPLOY on push - requires explicit authorization

name: Deploy Surfboard

on:
  workflow_dispatch:
    inputs:
      deploy_key:
        description: 'Deploy passphrase (required)'
        required: true
        type: string
      reason:
        description: 'Reason for deployment'
        required: true
        type: string

concurrency:
  group: deploy-surfboard-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  authorize:
    name: Verify Authorization
    runs-on: ubuntu-latest
    steps:
      - name: Check deploy key
        run: |
          if [ "${{ inputs.deploy_key }}" != "${{ secrets.SURFBOARD_DEPLOY_KEY }}" ]; then
            echo "::error::Invalid deploy key. Only authorized agents can deploy."
            exit 1
          fi
          echo "Deploy authorized by: ${{ github.actor }}"
          echo "Reason: ${{ inputs.reason }}"

  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: authorize
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        working-directory: apps/surfboard
        run: npm ci

      - name: Build Next.js
        working-directory: apps/surfboard
        run: npm run build

      - name: Build for Cloudflare
        working-directory: apps/surfboard
        run: npm run build:cf

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/surfboard/.vercel/output/static --project-name=onde-surf
          workingDirectory: '.'

      - name: Verify deployment
        run: |
          echo "Waiting for deployment propagation..."
          sleep 30

          # Check if site is reachable
          HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" "https://onde.surf" 2>/dev/null || echo "000")

          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "307" ]; then
            echo "Deployment verified! onde.surf is live."
          else
            echo "Warning: Got HTTP $HTTP_CODE - site may still be propagating"
          fi

      - name: Notify success
        if: success()
        run: |
          echo "========================================"
          echo "DEPLOY SUCCESSFUL"
          echo "========================================"
          echo "Site: https://onde.surf"
          echo "Commit: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"
          echo "Reason: ${{ inputs.reason }}"
          echo "Time: $(date -u)"
          echo "========================================"
