import type { Metadata } from 'next';
import Script from 'next/script';

// Breadcrumb JSON-LD for /games
const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: 'https://onde.la',
    },
    {
      '@type': 'ListItem',
      position: 2,
      name: 'Games',
      item: 'https://onde.la/games',
    },
  ],
};

// Structured data for games collection
const gamesJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'CollectionPage',
  name: 'Onde Arcade - Educational Games for Kids',
  description: 'Fun educational games for kids! Math, words, puzzles, memory, drawing, music and more.',
  url: 'https://onde.la/games/arcade/',
  publisher: {
    '@type': 'Organization',
    name: 'Onde',
    url: 'https://onde.la',
  },
  hasPart: [
    {
      '@type': 'VideoGame',
      name: '2048',
      description: 'Slide numbered tiles to combine them and reach 2048!',
      url: 'https://onde.la/games/2048/',
      genre: ['Educational', 'Math'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'ABC Fun',
      description: 'Learn the alphabet with fun interactive games',
      url: 'https://onde.la/games/alphabet/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Asteroids',
      description: 'Navigate through space and destroy asteroids',
      url: 'https://onde.la/games/asteroids/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Breakout',
      description: 'Smash bricks with a bouncing ball',
      url: 'https://onde.la/games/breakout/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Bubble Pop',
      description: 'Pop colorful bubbles by matching three or more',
      url: 'https://onde.la/games/bubble-pop/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Bubbles',
      description: 'Tap and pop floating bubbles',
      url: 'https://onde.la/games/bubbles/',
      genre: ['Educational', 'Casual'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 2 },
    },
    {
      '@type': 'VideoGame',
      name: 'Catch',
      description: 'Catch falling objects before they hit the ground',
      url: 'https://onde.la/games/catch/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Coloring Book',
      description: 'Express your creativity with a digital coloring book',
      url: 'https://onde.la/games/coloring/',
      genre: ['Educational', 'Creative'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Connect 4',
      description: 'Drop discs to connect four in a row',
      url: 'https://onde.la/games/connect4/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Counting Fun',
      description: 'Learn to count with colorful objects and fun animations',
      url: 'https://onde.la/games/counting/',
      genre: ['Educational', 'Math'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Crossword',
      description: 'Solve crossword puzzles with kid-friendly clues',
      url: 'https://onde.la/games/crossword/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 6 },
    },
    {
      '@type': 'VideoGame',
      name: 'Dino Runner',
      description: 'Run, jump, and dodge obstacles with the pixel dinosaur',
      url: 'https://onde.la/games/dino/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Draw',
      description: 'Free drawing canvas with brushes, colors, and tools',
      url: 'https://onde.la/games/draw/',
      genre: ['Educational', 'Creative'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Flappy Bird',
      description: 'Tap to fly through pipes',
      url: 'https://onde.la/games/flappy/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Fortune Cookie',
      description: 'Crack open a virtual fortune cookie and discover your fortune',
      url: 'https://onde.la/games/fortune-cookie/',
      genre: ['Educational', 'Casual'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Hangman',
      description: 'Guess the hidden word letter by letter',
      url: 'https://onde.la/games/hangman/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 5 },
    },
    {
      '@type': 'VideoGame',
      name: 'Space Invaders',
      description: 'Defend Earth from alien invaders',
      url: 'https://onde.la/games/invaders/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Jigsaw Puzzle',
      description: 'Piece together beautiful jigsaw puzzles online',
      url: 'https://onde.la/games/jigsaw/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Kids Chef Studio',
      description: 'Become a chef and cook delicious recipes',
      url: 'https://onde.la/games/kids-chef-studio/',
      genre: ['Educational', 'Creative'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Matching Game',
      description: 'Match pairs of cards to clear the board',
      url: 'https://onde.la/games/matching/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Math Quest',
      description: 'Fun math adventures for kids',
      url: 'https://onde.la/games/math/',
      genre: ['Educational', 'Math'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Maze Runner',
      description: 'Find your way through tricky mazes',
      url: 'https://onde.la/games/maze/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Memory',
      description: 'Flip cards and find matching pairs',
      url: 'https://onde.la/games/memory/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Minesweeper',
      description: 'Classic logic puzzle - clear the minefield',
      url: 'https://onde.la/games/minesweeper/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Moonlight Magic House',
      description: 'Explore a magical house under the moonlight',
      url: 'https://onde.la/games/moonlight-magic-house/',
      genre: ['Educational', 'Creative'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Music Maker',
      description: 'Create your own music with virtual instruments',
      url: 'https://onde.la/games/music/',
      genre: ['Educational', 'Music'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Pong',
      description: 'Classic table tennis arcade game',
      url: 'https://onde.la/games/pong/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Sliding Puzzle',
      description: 'Slide tiles into the correct order to complete the picture',
      url: 'https://onde.la/games/puzzle/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Quiz Challenge',
      description: 'Test your knowledge with fun trivia questions',
      url: 'https://onde.la/games/quiz/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 5 },
    },
    {
      '@type': 'VideoGame',
      name: 'Reaction Time',
      description: 'Test your reaction time with this quick-fire challenge',
      url: 'https://onde.la/games/reaction/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Rhythm Game',
      description: 'Hit the beats in time with the music',
      url: 'https://onde.la/games/rhythm/',
      genre: ['Educational', 'Music'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Scratch Card',
      description: 'Scratch and reveal hidden surprises',
      url: 'https://onde.la/games/scratch/',
      genre: ['Arcade', 'Casual'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Simon Says',
      description: 'Follow the pattern of lights and sounds',
      url: 'https://onde.la/games/simon/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Skin Creator',
      description: 'Create custom Minecraft skins with AI-powered editor',
      url: 'https://onde.la/games/skin-creator/',
      genre: ['Educational', 'Creative'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 6 },
    },
    {
      '@type': 'VideoGame',
      name: 'Lucky Slots',
      description: 'Spin the reels and match symbols',
      url: 'https://onde.la/games/slots/',
      genre: ['Arcade', 'Casual'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Spot the Difference',
      description: 'Compare two pictures and find all the differences',
      url: 'https://onde.la/games/spot-difference/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Sudoku',
      description: 'Solve number puzzles with multiple difficulty levels',
      url: 'https://onde.la/games/sudoku/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Tic Tac Toe',
      description: 'Classic X and O strategy game',
      url: 'https://onde.la/games/tictactoe/',
      genre: ['Educational', 'Puzzle'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 4 },
    },
    {
      '@type': 'VideoGame',
      name: 'Typing Practice',
      description: 'Improve your typing speed and accuracy',
      url: 'https://onde.la/games/typing/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 5 },
    },
    {
      '@type': 'VideoGame',
      name: 'Typing Race',
      description: 'Race against time by typing words as fast as you can',
      url: 'https://onde.la/games/typing-race/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 6 },
    },
    {
      '@type': 'VideoGame',
      name: 'Whack-a-Mole',
      description: 'Whack the moles as they pop up from their holes',
      url: 'https://onde.la/games/whack/',
      genre: ['Arcade', 'Educational'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Spin the Wheel',
      description: 'Spin the colorful wheel and see where it lands',
      url: 'https://onde.la/games/wheel/',
      genre: ['Arcade', 'Casual'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 3 },
    },
    {
      '@type': 'VideoGame',
      name: 'Word Puzzle',
      description: 'Unscramble letters and find hidden words',
      url: 'https://onde.la/games/word-puzzle/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 5 },
    },
    {
      '@type': 'VideoGame',
      name: 'Wordle',
      description: 'Guess the five-letter word in six tries',
      url: 'https://onde.la/games/wordle/',
      genre: ['Educational', 'Language'],
      audience: { '@type': 'PeopleAudience', suggestedMinAge: 6 },
    },
  ],
};

export const metadata: Metadata = {
  title: 'Onde Arcade - Educational Games for Kids | Onde',
  description: 'Fun educational games for kids! Math, words, puzzles, memory, drawing, music and more. Safe and ad-free learning games.',
  keywords: [
    'educational games for kids',
    'learning games',
    'kids games',
    'safe games for children',
    'math games',
    'puzzle games',
    'memory games',
    'drawing games',
  ],
  openGraph: {
    title: '🎮 Onde Arcade - Educational Games for Kids!',
    description: 'Fun educational games for children. Math, words, puzzles, memory, drawing, music and more. Safe and ad-free!',
    url: 'https://onde.la/games/arcade/',
    siteName: 'Onde',
    images: [
      {
        url: '/images/og-games.png',
        width: 1200,
        height: 630,
        alt: 'Onde Arcade - Educational Games for Kids',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: '🎮 Onde Arcade - Educational Games for Kids!',
    description: 'Fun educational games for children. Safe and ad-free!',
    images: ['/images/og-games.png'],
    creator: '@Onde_FRH',
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://onde.la/games/arcade/',
  },
};

export default function GamesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Script
        id="games-breadcrumb-jsonld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <Script
        id="games-jsonld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(gamesJsonLd) }}
      />
      {children}
    </>
  );
}
