#!/bin/bash
# =============================================================================
# ONDE DAILY REPORT
# Sends a daily status summary to Telegram
# =============================================================================

set -e

# Configuration
TELEGRAM_BOT_TOKEN="8528268093:AAGNZUcYBm8iMcn9D_oWr565rpxm9riNkBM"
TELEGRAM_CHAT_ID="7505631979"
ONDE_DIR="/Users/mattiapetrucciani/CascadeProjects/Onde"
LOG_FILE="/Users/mattiapetrucciani/CascadeProjects/Onde/automation/logs/daily-report.log"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Send Telegram message
send_telegram() {
    local message="$1"
    curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d "chat_id=${TELEGRAM_CHAT_ID}" \
        -d "text=$message" \
        -d "parse_mode=HTML" > /dev/null
}

# Get disk usage
get_disk_usage() {
    df -h / | tail -1 | awk '{print $5}'
}

# Get memory usage
get_memory_usage() {
    vm_stat | grep "Pages active" | awk '{print $3}' | tr -d '.'
}

# Count running services
get_running_services() {
    launchctl list | grep -c -E "(frh|onde|freeriverhouse)" || echo "0"
}

# Get git status summary
get_git_summary() {
    cd "$ONDE_DIR"
    local branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    local commits_today=$(git log --since="midnight" --oneline 2>/dev/null | wc -l | tr -d ' ')
    local uncommitted=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    echo "$branch|$commits_today|$uncommitted"
}

# Get bot uptime
get_bot_uptime() {
    local pid=$(pgrep -f "autonomous-bot.js" | head -1)
    if [ -n "$pid" ]; then
        ps -o etime= -p "$pid" | tr -d ' '
    else
        echo "not running"
    fi
}

# Check log files for errors
get_error_summary() {
    local bot_log="/tmp/frh-onde-bot.log"
    local errors_24h=0

    if [ -f "$bot_log" ]; then
        # Count errors from the last 24 hours (approximate)
        errors_24h=$(tail -500 "$bot_log" | grep -c -i "error" || echo "0")
    fi

    echo "$errors_24h"
}

# Get books in production
get_books_status() {
    local books_dir="$ONDE_DIR/books"
    if [ -d "$books_dir" ]; then
        local total=$(find "$books_dir" -name "*.pdf" -o -name "*.epub" 2>/dev/null | wc -l | tr -d ' ')
        echo "$total"
    else
        echo "0"
    fi
}

# Main report generation
main() {
    log "Generating daily report..."

    # Gather data
    local disk_usage=$(get_disk_usage)
    local running_services=$(get_running_services)
    local git_info=$(get_git_summary)
    local git_branch=$(echo "$git_info" | cut -d'|' -f1)
    local commits_today=$(echo "$git_info" | cut -d'|' -f2)
    local uncommitted=$(echo "$git_info" | cut -d'|' -f3)
    local bot_uptime=$(get_bot_uptime)
    local errors_24h=$(get_error_summary)
    local books_count=$(get_books_status)

    # Determine overall status
    local status_emoji="OK"
    if [ "$errors_24h" -gt 20 ]; then
        status_emoji="WARN"
    fi

    # Build message
    local message="<b>ONDE DAILY REPORT</b>
$(date '+%A, %d %B %Y')

<b>System Status:</b> $status_emoji
<b>Disk Usage:</b> $disk_usage
<b>Services Running:</b> $running_services

<b>Bot Status:</b>
- Uptime: $bot_uptime
- Errors (24h): $errors_24h

<b>Development:</b>
- Branch: $git_branch
- Commits today: $commits_today
- Uncommitted changes: $uncommitted

<b>Content:</b>
- Books/ePubs: $books_count

---
<i>Auto-generated by Onde Automation</i>
<code>Next report in 24h</code>"

    # Send report
    send_telegram "$message"
    log "Daily report sent successfully"
}

main "$@"
